server:
  port: 8002
  servlet:
    context-path: /payroll/api
spring:
  application:
    name: hr-payroll
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/ms-payroll?allowPublicKeyRetieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

hr-payroll:
  rabbitmq:
    exchange: hrpayroll.exchange
    routingkey: hr.payroll.key

hr-worker:
  rabbitmq:
    queue: workers.queue