server:
  port: 8001
  servlet:
    context-path: /worker/api
spring:
  application:
    name: hr-worker
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/ms-worker?allowPublicKeyRetieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

hr-worker:
  rabbitmq:
    exchange: hrworker.exchange
    routingKey: hrworker.key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka